export const Bitmoji = [
  {man1: 'https://i.ibb.co/RB31dwm/m1.jpg'},
  {man2: 'https://i.ibb.co/nDYhhTW/m2.jpg'},
  {man3: 'https://i.ibb.co/BGH2VSX/m3.jpg'},
  {man4: 'https://i.ibb.co/hBfV59c/m4.jpg'},
  {man5: 'https://i.ibb.co/6R5XCVX/m16.jpg'},
  {man6: 'https://i.ibb.co/b2FvK0N/m11.jpg'},
  // {man7: 'https://i.imghippo.com/files/T6AiD1729458377.jpg'},
  // {man8: 'https://i.imghippo.com/files/3kFpK1729458401.jpg'},
  // {man9: 'https://i.imghippo.com/files/pn7dI1729458425.jpg'},
  // {man10: 'https://drive.google.com/uc?export=view&id=1XFSFiPtwOv0MHTuuyupY3U-QKcVbPX-l'},
  // {man11: 'https://drive.google.com/uc?export=view&id=1S7pyArR6j1X4xCQtUfw8Gxi5Ufpcj6mv'},
  // {man12: 'https://drive.google.com/uc?export=view&id=1PMIMXYQZl5QHRJwLlfrZ50gzJzmIQ9tt'},
  // {man13: 'https://drive.google.com/uc?export=view&id=1T-mFAgdwenCq4CMm6AJv3bO1FWk3w12f'},
  // {man14: 'https://drive.google.com/uc?export=view&id=1PAxA4MrpRUeG2Jl_3KyMKbvb9Gp9Sft9'},
  // {man15: 'https://drive.google.com/uc?export=view&id=1nlCkbSkVQq89mDQhObPJlQDVLsS3Yjr7'},
  // {man16: 'https://drive.google.com/uc?export=view&id=1VqqotOnxrTk_y48bJowFAzvN1zgiHrSe'},
  // {man17: 'https://drive.google.com/uc?export=view&id=1t00MWeEYIBsZzSSY4M71Z7bpy-5DGxBc'},
  {fem1: 'https://i.ibb.co/Yk8vfqM/fem1.jpg'},
  {fem2: 'https://i.ibb.co/3ykryP8/fem2.jpg'},
  {fem3: 'https://i.ibb.co/vswCFz0/fem3.jpg'},
  {fem4: 'https://i.ibb.co/fY3PmfL/fem4.jpg'},
  {fem5: 'https://i.ibb.co/FKRsX83/fem5.jpg'},
  {fem6: 'https://i.ibb.co/rddv7Tw/fem6.jpg'}
];
